version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  win: circleci/windows@1

executors:
  mac:
    macos:
      xcode: "10.1.0"

jobs:
  win-test:
    working_directory: ~/app
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache

      # if you want to test execa's behavior on Windows
      # - run: node ./scripts/test-execa

      - run:
          name: 'Start server'
          command: npm run start:ci:windows
          background: true

      - run:
          name: 'Run Cypress tests'
          command: npm run e2e:record -- --env circle=true
          no_output_timeout: '1m'
      - store_artifacts:
          path: cypress\screenshots
      - store_artifacts:
          path: cypress\videos

  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release

workflows:
  linux-build:
    jobs:
      - cypress/install:
          name: 'Linux install'
          build: 'npm run build'
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info

      - cypress/run:
          name: '3 machines'
          requires:
            - Linux install
          record: true
          parallel: true
          parallelism: 3
          group: '3x-electron on CircleCI'
          start: 'npm run start:ci'

      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - 3 machines