version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  win: circleci/windows@1



workflows:
  linux-build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          name: 'Linux install'
          # and builds the app using this command
          build: 'npm run build'
          post-steps:
            # show Cypress cache folder and binary versions
            # to check if we are caching previous binary versions
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info

      # runs on 3 machines, load balances tests
      # and records on Cypress Dashboard
      - cypress/run:
          # name this job because we are running "cypress/run" several times
          # with different parameters
          name: '3 machines'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          record: true # record results on Cypress dashboard
          parallel: true # load balance all tests
          parallelism: 3 # across 3 machines
          group: '3x-electron on CircleCI' # name this group
          start: 'npm run start:ci' # start server before running tests

      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - 3 machines