version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1

workflows:
  linux-build:
    jobs:
      - cypress/install:
          name: 'Linux install'
          build: 'npm run build'
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info

      - cypress/run:
          name: '3 machines'
          requires:
            - Linux install
          record: true
          parallel: true
          parallelism: 3
          group: '3x-electron on CircleCI'
          start: 'npm run start:ci'

      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - 3 machines